### ISSUE TITLE
correctly using heracles on a localhost

### ISSUE THREAD

**Issue by aJonathanSchneider** [HydraCG/Heracles.ts#53] opened 2019-02-13 08:11 UTC
I looked at the tests and all the IDs there are relative to the server, e.g. ` "@id": "/api/people"`, However, my server returns json-ld with a domain name ` "@id": "http://mydomain.com/api/people",`

What's the correct way to use heracles on a localhost?

Currently I'm rewriting the getResource-Function to point any requests to the test-server running on localhost. The entrypoint's hypermedia gets a mixture of both: "iri"-property is from localhost, "@id" is "mydomain". Here's my HydraClient-initialization:

`private static initHydra(): HydraClientAPI {
    let rv: HydraClientAPI = new HydraClientAPI();
    let factory: HydraClientFactory = new HydraClientFactory();
    rv.hc = factory.withDefaults().andCreate() as HydraClient;
    rv.hc.getResource = async (urlOrResource) => {
      //START getUrl
      let url: any = urlOrResource;
      if (typeof url === "object") {
        url = !!url.target ? url.target.iri : url.iri;
      }
      if (!!!url) {
        throw new Error(HydraClient.noUrlProvided);
      }
      //END getUrl
      serverURLMap.forEach((val, key) => {
        if ((url as string).startsWith(key)) {
          url = (url as string).replace(key, val);
        }
      });
      const response = await fetch(url);
      if (response.status !== 200) {
        throw new Error(HydraClient.invalidResponse + response.status);
      }
      const hypermediaProcessor = rv.hc.getHypermediaProcessor(response);
      if (!hypermediaProcessor) {
        throw new Error(HydraClient.responseFormatNotSupported);
      }
      const result = await hypermediaProcessor.process(response, rv.hc);
      Object.defineProperty(result, "iri", {
        value: response.url
      });
      return result;
    };
    rv.setHydraApiDoc(hydraApiDocURL);
    return rv;
  }`

**Comment by alien-mcl** [comment] 2019-02-13 20:10
I'm not sure I understand the problem. Urls are resolved by JSON-LD API.
Heracles.ts does indeed combine relative urls when resolving links and operation targets using a base url which is obtained from the response of the initial request made.

If your server returns absolute urls, Heracles.ts won't interfere with any additional logic that will rewrite those urls. One moment in time I was thinking about possibility of injecting an HTTP api instead of using `fetch` directly - this would allow developer to come with a request interceptor that would amend the request (and it's URL) before the call is invoked. Would that help you?

Could you please give a usage example and what the issue is?

**Comment by aJonathanSchneider** [comment] 2019-02-14 09:21
About HTTP api injection: That would be nice, NSwag handles this in a way that fetch or a modified version of it can still be used, here's an example: https://github.com/RSuter/NSwag/blob/c2c3ad24fd1ef4e434a4a2fdc7c224c0c6f61771/src/NSwag.Integration.TypeScriptWeb/scripts/serviceClientsFetch.ts

About the domain vs relative paths: I've rewritten the integration test to explain what I expected the HydraClient to return: https://github.com/aJonathanSchneider/Heracles.ts/blob/master/integration-tests/Shnyder-server.spec.ts

When Heracles interprets the Hydra API my server returns, I'd like to show the user the collection's URL as http://mydomain.com/mycollection instead of http://localhost:port/mycollection (because the user defined it like that in the apiDocumentation).

**Comment by alien-mcl** [comment] 2019-02-14 19:53
Hmm - correct me if I'm wrong.

My understanding is you'd like Heracles.ts to remap possibly all Urls' domain (and protocol) matching some pattern with another one that were obtained from the server?

How would you de-reference those links then? Does the other domain provide these resources as well?

Probably there are other implications I don't see. If is only for displaying purposes. maybe it should be re-maped in the view somewhere?

Nevertheless, I think some HTTP interception mechanism should allow you to come with that custom logic.

**Comment by aJonathanSchneider** [comment] 2019-02-15 06:39
Yes I think HTTP interception could solve that problem.

Maybe I should explain my use-case so that it's clearer why I need my server to handle that:

- I'm using the Hydra-ApiDocumentation as a declaration to generate endpoints on a server. Because both Hydra and schema.org evolve over time, I need to get a snapshot of the "state of Linked Data". So that when I define an _schema:AddAction_ on a _hydra:Collection_ for a _schema:Product_, it will look up those types in the server instead of online (it's sort of version-management).
- when I'm running the server locally, I want to tell the client which endpoints there currently are, and which properties on e.g. _schema:Product_ can be set (in the version of _schema:Product_ my server knows about)
- otherwise changes in datamodels outside of my control could change my server's behaviour. So I want to combine the openess of Linked Data with deterministic behaviour, hydra in the middle as a declarative protocol

**Comment by alien-mcl** [comment] 2019-02-17 19:49
I've made a PR #54 - it enables the client to use custom HTTP facility. I hope it will allow you to come with your custom logic without any hacks on the client.

**Comment by alien-mcl** [comment] 2019-04-01 19:15
I assume @aJonathanSchneider that this can be closed now as the PR #54 was already merged.

**Closed by alien-mcl** 2019-04-01 19:15 UTC
