### ISSUE TITLE
Apidocumentation instance set entrypoint property as undefined

### ISSUE THREAD

**Issue by serchmtz** [HydraCG/Heracles.ts#272] opened 2021-11-13 02:09 UTC
Hello.
When I call the following function:
```ts
const testHeraclesApiDoc = async () => {
  let hydraClient = HydraClientFactory.configure()
    .withDefaults()
    .withAllLinks()  
    .andCreate();
  const apiDoc = await hydraClient.getApiDocumentation("http://localhost:8080/api");
  console.log(await apiDoc.getEntryPoint());  
};
```
I get the following error:
```
Uncaught (in promise) Error: There was no Url provided.
    getUrl HydraClient.js:111
    getResource HydraClient.js:62
    getEntryPoint factories.js:13
    testHeraclesApiDoc App.tsx:13
HydraClient.js:111
    testHeraclesApiDoc App.tsx:13
    AsyncFunctionThrow self-hosted:698
```
I am trying to use heracles.ts in a react application that consumes a mockup hydra API wich explicitly defines its entry point. This is the json-ld output of the documentation path:

```json
{
  "@id": "api/vocab",
  "@type": "hydra:ApiDocumentation",
  "hydra:entrypoint": "http://localhost:8080/api",
  "hydra:supportedClass": [
    {
      "@id": "api/vocab#EntryPoint",
      "@type": [
        "hydra:Class",
        "sh:Shape"
      ],
      "hydra:description": "The main entry point of the API",
      "hydra:supportedOperation": {
        "@type": "hydra:Operation",
        "hydra:description": "The API main entry point",
        "hydra:method": "GET",
        "hydra:returns": {
          "@id": "api/vocab#EntryPoint"
        }
      },
      "hydra:supportedProperty": {
        "@id": "api/vocab#personas",
        "@type": "hydra:SupportedProperty",
        "hydra:property": {
          "@id": "api/vocab#personas-link",
          "@type": "hydra:Link",
          "rdfs:comment": "Enlace a la colección de personas",
          "rdfs:label": "personas-link",
          "rdfs:range": {
            "@id": "api/vocab#PersonaCollection"
          },
          "hydra:supportedOperation": [
            {
              "@type": "hydra:Operation",
              "hydra:method": "GET",
              "hydra:returns": {
                "@id": "api/vocab#PersonaCollection"
              }
            },
            {
              "@type": "hydra:Operation",
              "hydra:expects": {
                "@id": "http://www.personas-mexico.org/persona#Persona"
              },
              "hydra:method": "POST",
              "hydra:returns": {
                "@id": "http://www.personas-mexico.org/persona#Persona"
              }
            }
          ]
        }
      },
      "hydra:title": "EntryPoint"
    },
    {
      "@id": "api/vocab#PersonaCollection",
      "@type": [
        "hydra:Class",
        "hydra:Collection"
      ],
      "hydra:description": "Coleción de todas las personas",
      "hydra:supportedOperation": [],
      "hydra:title": "PersonaCollection",
      "lvz:memberClass": "http://www.personas-mexico.org/persona#Persona"
    },
    {
      "@id": "http://www.personas-mexico.org/persona#Persona",
      "@type": [
        "hydra:Class",
        "sh:Shape"
      ],
      "hydra:description": "Una persona",
      "hydra:supportedOperation": [
        {
          "@type": "hydra:Operation",
          "hydra:method": "GET",
          "hydra:returns": {
            "@id": "http://www.personas-mexico.org/persona#Persona"
          }
        },
        {
          "@type": "hydra:Operation",
          "hydra:method": "DELETE"
        }
      ],
      "hydra:supportedProperty": [
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tieneSexo",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "El género o sexo de la persona",
            "rdfs:label": "tieneSexo",
            "rdfs:range": {
              "@id": "xsd:string"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": true
        },
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tieneNombre",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "El nombre de la persona",
            "rdfs:label": "tieneNombre",
            "rdfs:range": {
              "@id": "xsd:string"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": true
        },
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tieneSegundoApellido",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "El segundo apellido de la persona",
            "rdfs:label": "tieneSegundoApellido",
            "rdfs:range": {
              "@id": "xsd:string"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": false
        },
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tienePrimerApellido",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "El primer apellido de la persona",
            "rdfs:label": "tienePrimerApellido",
            "rdfs:range": {
              "@id": "xsd:string"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": true
        }
      ],
      "hydra:title": "Persona"
    },
    {
      "@id": "http://www.personas-mexico.org/persona#Medico",
      "@type": [
        "hydra:Class",
        "sh:Shape"
      ],
      "hydra:description": "Un médico",
      "hydra:supportedOperation": [
        {
          "@type": "hydra:Operation",
          "hydra:method": "GET",
          "hydra:returns": {
            "@id": "http://www.personas-mexico.org/persona#Medico"
          }
        },
        {
          "@type": "hydra:Operation",
          "hydra:method": "DELETE"
        }
      ],
      "hydra:supportedProperty": [
        {
          "@id": "http://www.personas-mexico.org/persona#info-basica-link",
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#info-basica",
            "@type": "hydra:Link",
            "rdfs:comment": "Información básica de una persona",
            "rdfs:label": "info-basica",
            "rdfs:range": {
              "@id": "http://www.personas-mexico.org/persona#Persona"
            },
            "hydra:supportedOperation": [
              {
                "@type": "hydra:Operation",
                "hydra:method": "GET",
                "hydra:returns": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                }
              },
              {
                "@type": "hydra:Operation",
                "hydra:expects": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                },
                "hydra:method": "POST",
                "hydra:returns": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                }
              }
            ]
          },
          "hydra:readonly": true
        },
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tieneCedulaProfesional",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "La cédula profesional de un médico",
            "rdfs:label": "tieneCedulaProfesional",
            "rdfs:range": {
              "@id": "xsd:string"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": true
        }
      ],
      "hydra:title": "Medico"
    },
    {
      "@id": "http://www.personas-mexico.org/persona#Paciente",
      "@type": [
        "hydra:Class",
        "sh:Shape"
      ],
      "hydra:description": "Un paciente",
      "hydra:supportedOperation": [
        {
          "@type": "hydra:Operation",
          "hydra:method": "GET",
          "hydra:returns": {
            "@id": "http://www.personas-mexico.org/persona#Paciente"
          }
        },
        {
          "@type": "hydra:Operation",
          "hydra:method": "DELETE"
        }
      ],
      "hydra:supportedProperty": [
        {
          "@id": "http://www.personas-mexico.org/persona#info-basica-link",
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#info-basica",
            "@type": "hydra:Link",
            "rdfs:comment": "Información básica de una persona",
            "rdfs:label": "info-basica",
            "rdfs:range": {
              "@id": "http://www.personas-mexico.org/persona#Persona"
            },
            "hydra:supportedOperation": [
              {
                "@type": "hydra:Operation",
                "hydra:method": "GET",
                "hydra:returns": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                }
              },
              {
                "@type": "hydra:Operation",
                "hydra:expects": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                },
                "hydra:method": "POST",
                "hydra:returns": {
                  "@id": "http://www.personas-mexico.org/persona#Persona"
                }
              }
            ]
          },
          "hydra:readonly": true
        },
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "http://www.personas-mexico.org/persona#tieneFechaDeNacimiento",
            "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "rdfs:comment": "La fecha de nacimiento de la persona",
            "rdfs:label": "tieneFechaDeNacimiento",
            "rdfs:range": {
              "@id": "xsd:date-time"
            },
            "hydra:supportedOperation": []
          },
          "hydra:required": true
        }
      ],
      "hydra:title": "Paciente"
    }
  ],
  "lvz:entrypointClass": "http://localhost:8080/api/vocab#EntryPoint",
  "@context": {
    "@vocab": "http://localhost:8080/api/vocab#",
    "@base": "http://localhost:8080/",
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "sh": "http://www.w3.org/ns/shacl#"
  }
}
```

From what I see the error is generated because the `ApiDocumentation` object obtained does not set the `entryPoint` property. This is the output of the object:

![image](https://user-images.githubusercontent.com/34547100/141601423-76cd2773-cec7-4779-80ad-eeeefae3a30a.png)

I don't know if this is a bug or maybe I'm missing something.

**Comment by alien-mcl** [comment] 2021-11-13 12:40
Hi @serchmtz 

Thanks for raising this issue. Just to ensure, I assume your API returns a link header to provide a valid API documentation Url.

From a quick integration test I can see that the entrypoint property of the API documentation gets resolved by the JSON-LD processor as a value while it should be a resource.

I'll come back to you ASAP with clarification what went wrong.

**Comment by alien-mcl** [comment] 2021-11-13 12:43
Same thing happens when pasted to JSON-LD playground - entrypoint becomes a literal rather than a resource

**Comment by alien-mcl** [comment] 2021-11-13 14:33
OK. I've found it. The issue is related to JSON-LD itself. You'll need to either
- add `http://www.w3.org/ns/hydra/context.jsonld` to your `@context` (this will require JSON-LD v1.1) and replace all `hydra` related terms to those defined in the standard hydra JSON-LD context (these are not pefixed with `hydra:`)
- define `hydra` related terms (or at least those you use) within your context, then you'll be able to use `hydra:` prefixed terms.
Please let me know if it works for you.

**Comment by serchmtz** [comment] 2021-11-13 21:24
Thanks for your response @alien-mcl, I'm still grasping  Hydra and JSON-LD, so, sorry if I rised this issue in the wrong place. Also thanks for the amazing job that all this community is doing.

I can confirm that is an issue in the generated context.

With the following context, the `hydra:entrypoint` term becomes a resource when pasted to JSON-LD playground and also the property of the `ApiDocumentation` object is correct.

```json
"@context": {
    "hydra:property": {
      "@type": "@vocab"
    },
    "hydra:supportedProperty": {
      "@type": "@id"
    },
    "hydra:expects": {
      "@type": "@vocab"
    },
    "hydra": "http://www.w3.org/ns/hydra/core#",
    "@vocab": "http://localhost:8080/api/vocab#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "@base": "http://localhost:8080/",
    "hydra:supportedClass": {
      "@type": "@vocab"
    },
    "hydra:returns": {
      "@type": "@vocab"
    },
    "sh": "http://www.w3.org/ns/shacl#",
    "hydra:supportedOperation": {
      "@type": "@id"
    },
    "hydra:entrypoint": {
      "@type": "@id"
    },
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  }
```
![image](https://user-images.githubusercontent.com/34547100/141658411-07566e78-8c62-4a2d-913e-6748eb03fc5b.png)

So the issue is on the tool that I'm using to generate the Hydra API, [Levanzo](https://github.com/antoniogarrote/levanzo). It seems that, by default, the generated context for the API documentation does not conform with what a hydra client expects.  Actually, I'm using a forked version of Levanzo, so I can change this for my project.

**Comment by alien-mcl** [comment] 2021-11-14 21:18
I'm not familiar with that tool. I'll consider adding another context with `hydra:` prefixed terms. For the meanwhile - let me close that one.

**Closed by alien-mcl** 2021-11-14 21:18 UTC
